Update sc2 script with gallium nine and d3dcompiler_47

diff --git a/bin/sc2 b/bin/sc2
--- a/bin/sc2
+++ b/bin/sc2
@@ -1,7 +1,111 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-export WINEPREFIX=/home/chris/.local/share/wineprefixes/sc2
-export WINE=wine
-export sc2="C://Program Files/StarCraft II/Starcraft II.exe"
+# WINEPATH='/opt/wine-tkg-git-sc2-4.0.r9.g60f0f503'
+# export WINE="$WINEPATH/bin/wine"
+WINE="$(command -v wine)"
+export WINE
+export WINEPREFIX="$HOME/.local/share/wineprefixes/sc2"
+export WINEDEBUG=-all
+export WINEESYNC=1
 
-$WINE explorer /desktop=sc2,1920x1080 $sc2
+export SC2="C://Program Files (x86)/StarCraft II/Support64/SC2Switcher_x64.exe"
+export LAUNCHPAD="C://Program Files (x86)/Battle.net/Battle.net Launcher.exe"
+
+case "$1" in
+    install)
+        INSTALLER_URL='https://www.battle.net/download/getInstallerForGame?os=win&locale=enUS&version=LIVE&gameProgram=STARCRAFT_2'
+        INSTALLER_MD5='2fe83831f3f71bdc2928967aaba9b79e'
+
+        INSTALLER="$HOME/.cache/sc2_setup.exe"
+
+        ## Do not overwrite prefix. Run reset first.
+        if [[ -d "$WINEPREFIX" ]]; then
+            echo "Destination $WINEPREFIX exists. Aborting. Run $(basename "$0") reset."
+            exit 1
+        fi
+
+        winetricks win10 corefonts d3dcompiler_43 d3dcompiler_47 galliumnine02
+        wineserver -w
+
+        if [[ ! -f "$INSTALLER" ]]; then
+            curl -o "$INSTALLER" -L "$INSTALLER_URL"
+        fi
+
+        if [[ -f "$INSTALLER" ]]; then
+            MD5=$(md5sum "$INSTALLER")
+            if [[ "$MD5" = "$INSTALLER_MD5  $INSTALLER" ]]; then
+                "$WINE" "$INSTALLER"
+            else
+                echo "Installer did not pass md5 check. Removing and downloading again."
+                echo "Expected md5: $INSTALLER_MD5"
+                echo "Obtained m5: $MD5"
+
+                rm "$INSTALLER"
+                curl -o "$INSTALLER" -L "$INSTALLER_URL"
+                MD5=$(md5sum "$INSTALLER")
+                if [[ "$MD5" = "$INSTALLER_MD5  $INSTALLER" ]]; then
+                    "$WINE" "$INSTALLER"
+                else
+                    echo "Downloaded installer again, still did not pass md5 check. Aborting."
+                    echo "Expected md5: $INSTALLER_MD5"
+                    echo "Obtained m5: $MD5"
+                fi
+            fi
+        else
+            echo "The installation file could not be found at $INSTALLER"
+        fi
+        ;;
+
+    reset)
+        echo "this will completely remove $WINEPREFIX. This can not be undone."
+        read -p "Are you sure? " -n 1 -r
+
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            echo
+            echo -n "Nuking wineprefix... "
+            rm -rf "$WINEPREFIX"
+            echo "Done."
+        else
+            echo "Aborting."
+        fi
+        ;;
+
+    version)
+        echo "Wine path: ${WINE%%/bin/wine}"
+        echo "Wine version: $($WINE --version)"
+        ;;
+
+    config)
+        exec "${WINE%/*}/winecfg"
+        # exec winecfg
+        ;;
+
+    winetricks)
+        shift
+        exec winetricks "$@"
+        ;;
+
+    kill)
+        ps ux | grep -v grep | grep -v "sc2 kill\\|qutebrowser\\|firefox\\|chrome\\|chromium" | \
+            grep -i "windows\\|wineserver\\|sc2\\|starcraft\\|.exe\\|battle.net\\|wineconsole\\|awesomium\\|winetricks\\|winedbg\\|explorer.exe" | \
+            awk '{print $2}' | xargs kill -KILL
+        ;;
+
+    run)
+        shift
+        exec "$WINE" "$@"
+        ;;
+
+    launcher)
+        exec "$WINE" "$LAUNCHPAD" -Displaymode 1
+        ;;
+
+    *)
+      # taskset -c 0-2
+      "$WINE" "$SC2" -Displaymode 1
+      ;;
+
+
+esac
+
+# vim:ft=sh
